try_run(PYTHON_VERSION_RESULT PYTHON_VERSION_COMPILE
        ${CMAKE_BINARY_DIR}
        ${PROJECT_SOURCE_DIR}/cmake/PythonVersion.c
        CMAKE_FLAGS
          "-DLINK_LIBRARIES:STRING=${PYTHON_LIBRARIES}"
	  "-DINCLUDE_DIRECTORIES:STRING=${PYTHON_INCLUDE_DIRS}"
        COMPILE_OUTPUT_VARIABLE PYTHON_VERSION_COMPILE_OUTPUT
        RUN_OUTPUT_VARIABLE PYTHON_VERSION_RUN_OUTPUT)

if(NOT PYTHON_VERSION_COMPILE)
  message(FATAL_ERROR
    "Could not compile Python.h test program:\n\n${PYTHON_VERSION_COMPILE_OUTPUT}")
endif(NOT PYTHON_VERSION_COMPILE)

if(NOT CMAKE_CROSSCOMPILING)
  set(PYTHON_VERSION "${PYTHON_VERSION_RUN_OUTPUT}")

  message(STATUS "Python libraries version ${PYTHON_VERSION}")
else(NOT CMAKE_CROSSCOMPILING)
  message(STATUS "Cross compiling -> cannot derive Python libraries version")
endif(NOT CMAKE_CROSSCOMPILING)  

