try_run(TEST_HDF5_RESULT TEST_HDF5_COMPILE
        ${CMAKE_BINARY_DIR}
        ${PROJECT_SOURCE_DIR}/cmake/TestHDF5.c
        CMAKE_FLAGS
          "-DLINK_LIBRARIES:STRING=${HDF5_LIBRARIES}"
#          "-DINCLUDE_DIRECTORIES:STRING=${HDF5_INCLUDE_DIR}"
	  "-DINCLUDE_DIRECTORIES:STRING=${HDF5_INCLUDES}"
        COMPILE_OUTPUT_VARIABLE TEST_HDF5_COMPILE_OUTPUT
        RUN_OUTPUT_VARIABLE TEST_HDF5_RUN_OUTPUT)

if(NOT TEST_HDF5_COMPILE)
  message(FATAL_ERROR
    "Could not compile HDF5 test program:\n\n${TEST_HDF5_COMPILE_OUTPUT}")
endif(NOT TEST_HDF5_COMPILE)

if(NOT CMAKE_CROSSCOMPILING)
  if(TEST_HDF5_RESULT GREATER 0)
    message(FATAL_ERROR
      "Version mismatch between HDF5 headers and HDF5 library:\n${TEST_HDF5_RUN_OUTPUT}")
  endif(TEST_HDF5_RESULT GREATER 0)
endif(NOT CMAKE_CROSSCOMPILING)  

