try_run(TEST_HDF5_RESULT TEST_HDF5_COMPILE
        ${CMAKE_BINARY_DIR}
        ${PROJECT_SOURCE_DIR}/cmake/TestHDF5.c
        CMAKE_FLAGS
          "-DLINK_LIBRARIES:STRING=${HDF5_LIBRARIES}"
	  "-DINCLUDE_DIRECTORIES:STRING=${HDF5_INCLUDES}"
        COMPILE_OUTPUT_VARIABLE TEST_HDF5_COMPILE_OUTPUT
        RUN_OUTPUT_VARIABLE TEST_HDF5_RUN_OUTPUT)

if(NOT TEST_HDF5_COMPILE)
  message(FATAL_ERROR
    "Could not compile HDF5 test program:\n\n${TEST_HDF5_COMPILE_OUTPUT}")
endif(NOT TEST_HDF5_COMPILE)

if(NOT CMAKE_CROSSCOMPILING)
  if(TEST_HDF5_RESULT GREATER 0)
    message(FATAL_ERROR
      "Version mismatch between HDF5 headers and HDF5 library: ${TEST_HDF5_RUN_OUTPUT}")
  else(TEST_HDF5 RESULT GREATER 0)
    set(HDF5_VERSION "${TEST_HDF5_RUN_OUTPUT}")

    message(STATUS "HDF5 version ${HDF5_VERSION}")
  endif(TEST_HDF5_RESULT GREATER 0)
else(NOT CMAKE_CROSSCOMPILING)
  message(STATUS "Cross compiling -> assuming HDF5 headers and library versions match")
endif(NOT CMAKE_CROSSCOMPILING)  

